dist: trusty
sudo: required  # gives more RAM (otherwise memory error for TOM)
language: python
matrix:
  include:
  - python: "2.7"
    env: PYTORCH_URL=http://download.pytorch.org/whl/cpu/torch-0.4.0-cp27-cp27mu-linux_x86_64.whl
  - python: "3.5"
    env: PYTORCH_URL=http://download.pytorch.org/whl/cpu/torch-0.4.0-cp35-cp35m-linux_x86_64.whl
before_install:
  - pip install $PYTORCH_URL
  - pip install https://github.com/MIC-DKFZ/batchgenerators/archive/master.zip
install:
  - pip install .
script:
  - TractSeg -i examples/Diffusion_mrtrix_peaks.nii.gz --skip_peak_extraction --single_orientation
  - TractSeg -i examples/Diffusion_mrtrix_peaks.nii.gz --skip_peak_extraction --output_type TOM --single_orientation
  - TractSeg -i examples/Diffusion_mrtrix_peaks.nii.gz --skip_peak_extraction --output_type TOM --endings_segmentation
  - pytest